name: packagemap
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Read and write packages.map files.
homepage: http://www.dartlang.org
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
